### ISSUE TITLE
Request Ubuntu Touch version

### ISSUE THREAD

**Issue by idekovets** [jgibbon/Talefish#13] opened 2018-08-03 13:18 UTC
Good Day!

Please consider the possibility of porting your program to Ubuntu Touch.

Best regards!

**Comment by carlosgonz0** [comment] 2018-11-24 18:19
HI @jgibbon 
how much hard to port this to ubuntu touch? i am interested on the ubuntu-port too.
thanks of advance..

**Comment by jgibbon** [comment] 2018-11-24 18:51
I have not used UT yet and do not have a compatible device. Also I can not realistically imagine that someone would be willing to sponsor one for me just so I can l look at it and try to port this buggy application. :) 
(feel free to contact me if I am wrong...) 

From what I have heard about UT, some kind of port should be theoretically possible, though.

**Comment by carlosgonz0** [comment] 2018-11-25 01:16
always believe it @jgibbon : )
it is not a buggy app, in fact this  is the best audio-player in SFOS.

**Comment by jgibbon** [comment] 2023-02-06 08:22
Hi, I'll close this issue as I still don't have plans to port myself. 
But at least the qml components are a more organized now and things requiring silica itself should mostly be in one folder.

If anyone else wants to port, I'm open for collaboration – possibly in one repo. But keep in mind it's mostly UI stuff that makes Talefish special  – most of that would have to be recreated. Beneath that, it's _mostly_ a bog-standard qml audio player.

cheers!

**Closed as completed by jgibbon** 2023-02-06 08:22 UTC
Labels: help wanted
